### ISSUE TITLE
Komunikaty

### ISSUE THREAD

**Issue by Viking92** [Viking92/TIN-P2P#2]
Proponuję jednak zrobić jeden wielki komunikat. Wydaje mi się, że znacznie uprości to komunikację. A przy obsłudze tego, no to w zależności od tego, jaki to będzie komunikat, to będzie się brało pod uwagę tylko niektóre pola, a nie wszystko.

**Comment by mcybuls1** [comment]
Dla mnie szpoko jak już mówiłem
